[theme]
primaryColor = "#5367FF"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#121212"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
